# generated by datamodel-codegen:
#   filename:  egm_class_model_metadata.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Versioned schema identifier. Consumers MUST refuse unknown major versions.
    """

    field_1_2 = "1.2"


class Framework(Enum):
    """
    Artifact format. ONNX is the portable form; TensorRT is the deployment-platform-specific engine; PyTorch is the checkpoint format used during training.
    """

    onnx = "onnx"
    tensorrt = "tensorrt"
    pytorch = "pytorch"


class ModelArtifact(BaseModel):
    """
    Reference to the model file this metadata pairs with. Lives next to the artifact on disk (e.g., 'best.onnx' + 'best.model_metadata.json').
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    filename: str
    """
    Filename relative to this metadata file (e.g., 'best.onnx', 'engine.plan'). Resolver joins this with the directory of the metadata file.
    """
    framework: Framework
    """
    Artifact format. ONNX is the portable form; TensorRT is the deployment-platform-specific engine; PyTorch is the checkpoint format used during training.
    """
    sha256: str | None = Field(None, pattern="^[0-9a-f]{64}$")
    """
    Content hash of the artifact for tamper detection. Optional but strongly recommended for deployed models.
    """
    size_bytes: int | None = Field(None, ge=0)
    """
    Artifact size in bytes. Optional; primarily for sanity-checking against the on-disk file.
    """


class Semantics(Enum):
    """
    What the output value means. 'binary_logit' means apply sigmoid to get P(positive); 'binary_probability' means the value is already sigmoid-applied. Multi-class variants are equivalent for softmax/log-softmax outputs.
    """

    binary_logit = "binary_logit"
    binary_probability = "binary_probability"
    multiclass_logits = "multiclass_logits"
    multiclass_probabilities = "multiclass_probabilities"


class BandpassHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)
    """
    A band-edge frequency in Hz. The two-element array is [low, high]; both must be positive.
    """


class Scheme(Enum):
    """
    Normalization scheme applied per trace. 'zscore' = subtract the trace's mean and divide by its standard deviation (suits approximately-Gaussian signals; what the v1 classifier trains with). 'zero2one' = min-max rescale so the trace's minimum maps to 0.0 and maximum to 1.0 (useful when amplitude bounds are meaningful and the distribution is non-Gaussian). 'none' = pass the raw trace through unchanged (use only when the producer pipeline has already normalized upstream).
    """

    zscore = "zscore"
    zero2one = "zero2one"
    none = "none"


class Normalization(BaseModel):
    """
    Per-trace signal normalization applied at inference time. The v1 classifier consumes one bipolar trace per forward pass, so all schemes are computed from each trace's own samples — no global or per-channel statistics are recorded here. Any sensor- or hardware-level normalization (e.g. ADC-gain correction) is expected to happen upstream of this contract.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    scheme: Scheme
    """
    Normalization scheme applied per trace. 'zscore' = subtract the trace's mean and divide by its standard deviation (suits approximately-Gaussian signals; what the v1 classifier trains with). 'zero2one' = min-max rescale so the trace's minimum maps to 0.0 and maximum to 1.0 (useful when amplitude bounds are meaningful and the distribution is non-Gaussian). 'none' = pass the raw trace through unchanged (use only when the producer pipeline has already normalized upstream).
    """


class Preprocessing(BaseModel):
    """
    Signal-conditioning constants the runtime applies before inference, in the order listed here. Must match the preprocessing used during training; mismatch will silently degrade performance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    expected_fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate the model was trained at (Hz). Inference inputs at a different rate must be resampled before invocation.
    """
    expected_trace_samples: int = Field(..., gt=0)
    """
    Per-trace length in samples the model expects. Must match the time-axis dimension in input.shape.
    """
    bandpass_hz: list[BandpassHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz [low, high] applied at inference. Should match the bank's band_hz.
    """
    normalization: Normalization
    """
    Per-trace signal normalization applied at inference time. The v1 classifier consumes one bipolar trace per forward pass, so all schemes are computed from each trace's own samples — no global or per-channel statistics are recorded here. Any sensor- or hardware-level normalization (e.g. ADC-gain correction) is expected to happen upstream of this contract.
    """


class Decision(BaseModel):
    """
    Decision-rule constants applied to the model output to produce a class label.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    threshold: float = Field(..., ge=0.0, le=1.0)
    """
    Decision threshold applied to P(fibrotic). 0.5 unless calibration analysis recommends otherwise. For multi-class models this is the threshold for the positive class; multi-class extension may add per-class thresholds in a future schema version.
    """
    class_labels: list[str] = Field(..., min_length=2)
    """
    Human-readable class labels in the order matching the model's output index. For binary: ['healthy', 'fibrotic'] (index 0 = healthy, index 1 = fibrotic).
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class Dtype(Enum):
    """
    Floating-point element dtype. Used for both input and output tensors.
    """

    float32 = "float32"
    float16 = "float16"


class Input(BaseModel):
    """
    Expected input tensor spec. The ONNX graph itself encodes shape; this section is the deployment-time documentation of what the model assumes, used for sanity-checking incoming data before dispatch.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    ONNX input tensor name (e.g., 'signal'). Matches the ONNX graph's input.
    """
    shape: list[int | str]
    """
    Tensor shape. Integer for fixed dims, '?' (string) for dynamic dims. Example for the v1 EGM classifier: ['?', 1, 512] — dynamic batch axis, channel axis fixed at 1 (PyTorch Conv1d expects [batch, channels, length]; a single bipolar trace is one channel), trace length fixed at 512 samples. Keep the batch axis dynamic so the same ONNX serves both real-time scoring (batch=1) and offline bulk inference (batch=N) without re-export.
    """
    dtype: Dtype
    """
    Input element dtype.
    """


class Output(BaseModel):
    """
    Expected output tensor spec.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    ONNX output tensor name (e.g., 'logit').
    """
    shape: list[int | str]
    """
    Output tensor shape. Example for a single-logit binary classifier: ['?', 1].
    """
    dtype: Dtype
    """
    Output element dtype.
    """
    semantics: Semantics
    """
    What the output value means. 'binary_logit' means apply sigmoid to get P(positive); 'binary_probability' means the value is already sigmoid-applied. Multi-class variants are equivalent for softmax/log-softmax outputs.
    """


class EgmClassModelMetadata(BaseModel):
    """
    Preprocessing + inference-time constants paired with a deployed EGM-classifier model artifact (typically the ONNX file). Captures everything the runtime needs that is NOT encoded in the ONNX graph itself: expected sample rate, expected trace length, per-trace normalization scheme, decision threshold, model artifact hash, training provenance. Cross-language: consumed by Python (training-eval parity) and C++ (TensorRT inference). The field shape here (binary_logit semantics, single bipolar input, [batch, 1, T] tensor) is specific to the 1D EGM-classifier family — the middle '1' is the channel axis required by PyTorch Conv1d, not a multi-channel slot. Future model topologies (2D electrode grids, sparse 3D electrode point clouds) get their own schemas. Schema version 1.2 (from 1.1) added the optional `model_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). The model->run link is intentionally NOT stored here — this file carries only what a deployed model needs; the run.json's `produced_model_id` records that link from the run side.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Versioned schema identifier. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp at export time.
    """
    model_id: str | None = Field(
        None, pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$"
    )
    """
    Stable artifact ID of THIS model, e.g. 'model_egm_classifier_v1_5_2026-06-25'. The model's own cross-artifact identifier — this is what a run.json's `produced_model_id` points at. Optional for legacy metadata written before egm-contracts v0.5.0; egm-classifier stamps it at export time. Added 1.2.
    """
    model_artifact: ModelArtifact
    """
    Reference to the model file this metadata pairs with. Lives next to the artifact on disk (e.g., 'best.onnx' + 'best.model_metadata.json').
    """
    input: Input
    """
    Expected input tensor spec. The ONNX graph itself encodes shape; this section is the deployment-time documentation of what the model assumes, used for sanity-checking incoming data before dispatch.
    """
    output: Output
    """
    Expected output tensor spec.
    """
    preprocessing: Preprocessing
    """
    Signal-conditioning constants the runtime applies before inference, in the order listed here. Must match the preprocessing used during training; mismatch will silently degrade performance.
    """
    decision: Decision
    """
    Decision-rule constants applied to the model output to produce a class label.
    """
    training_provenance: dict[str, Any]
    """
    Where this model came from. Well-known keys: 'run_id' (identifier into the run.json that documents the training), 'run_json_path' (path to the run.json), 'training_bank_path' (path to the synthetic bank used for training), 'training_bank_schema_version' (the synthetic_bank schema version this bank conforms to, e.g. '1.0'), 'git_sha' (source repo state at training time). Additional keys are allowed for producer-specific provenance.
    """
