# generated by datamodel-codegen:
#   filename:  egm_class_model_metadata.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Versioned schema identifier. Consumers MUST refuse unknown major versions.
    """

    field_1_0 = "1.0"


class Framework(Enum):
    """
    Artifact format. ONNX is the portable form; TensorRT is the deployment-platform-specific engine; PyTorch is the checkpoint format used during training.
    """

    onnx = "onnx"
    tensorrt = "tensorrt"
    pytorch = "pytorch"


class ModelArtifact(BaseModel):
    """
    Reference to the model file this metadata pairs with. Lives next to the artifact on disk (e.g., 'best.onnx' + 'best.model_metadata.json').
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    filename: str
    """
    Filename relative to this metadata file (e.g., 'best.onnx', 'engine.plan'). Resolver joins this with the directory of the metadata file.
    """
    framework: Framework
    """
    Artifact format. ONNX is the portable form; TensorRT is the deployment-platform-specific engine; PyTorch is the checkpoint format used during training.
    """
    sha256: str | None = Field(None, pattern="^[0-9a-f]{64}$")
    """
    Content hash of the artifact for tamper detection. Optional but strongly recommended for deployed models.
    """
    size_bytes: int | None = Field(None, ge=0)
    """
    Artifact size in bytes. Optional; primarily for sanity-checking against the on-disk file.
    """


class Semantics(Enum):
    """
    What the output value means. 'binary_logit' means apply sigmoid to get P(positive); 'binary_probability' means the value is already sigmoid-applied. Multi-class variants are equivalent for softmax/log-softmax outputs.
    """

    binary_logit = "binary_logit"
    binary_probability = "binary_probability"
    multiclass_logits = "multiclass_logits"
    multiclass_probabilities = "multiclass_probabilities"


class BandpassHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)
    """
    A band-edge frequency in Hz. The two-element array is [low, high]; both must be positive.
    """


class Scheme(Enum):
    """
    Normalization scheme.
    """

    zscore = "zscore"
    minmax = "minmax"
    none = "none"


class StdItem(RootModel[float]):
    root: float = Field(..., gt=0.0)
    """
    Per-channel standard deviation applied as the scaling divisor during normalization. Must be strictly positive.
    """


class Normalization(BaseModel):
    """
    Per-channel signal normalization. For a 1-channel bipolar model the arrays are length 1. The scheme determines which fields are required: 'zscore' needs mean+std; 'minmax' would need min+max (add in a future schema version); 'none' needs neither.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    scheme: Scheme
    """
    Normalization scheme.
    """
    mean: list[float] | None = None
    """
    Per-channel mean (required for 'zscore'). Length must equal the input channel count.
    """
    std: list[StdItem] | None = None
    """
    Per-channel standard deviation (required for 'zscore'). Length must equal the input channel count.
    """


class Preprocessing(BaseModel):
    """
    Signal-conditioning constants the runtime applies before inference, in the order listed here. Must match the preprocessing used during training; mismatch will silently degrade performance.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    expected_fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate the model was trained at (Hz). Inference inputs at a different rate must be resampled before invocation.
    """
    expected_trace_samples: int = Field(..., gt=0)
    """
    Per-trace length in samples the model expects. Must match the time-axis dimension in input.shape.
    """
    bandpass_hz: list[BandpassHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz [low, high] applied at inference. Should match the bank's band_hz.
    """
    normalization: Normalization
    """
    Per-channel signal normalization. For a 1-channel bipolar model the arrays are length 1. The scheme determines which fields are required: 'zscore' needs mean+std; 'minmax' would need min+max (add in a future schema version); 'none' needs neither.
    """


class Decision(BaseModel):
    """
    Decision-rule constants applied to the model output to produce a class label.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    threshold: float = Field(..., ge=0.0, le=1.0)
    """
    Decision threshold applied to P(fibrotic). 0.5 unless calibration analysis recommends otherwise. For multi-class models this is the threshold for the positive class; multi-class extension may add per-class thresholds in a future schema version.
    """
    class_labels: list[str] = Field(..., min_length=2)
    """
    Human-readable class labels in the order matching the model's output index. For binary: ['healthy', 'fibrotic'] (index 0 = healthy, index 1 = fibrotic).
    """


class Dtype(Enum):
    """
    Floating-point element dtype. Used for both input and output tensors.
    """

    float32 = "float32"
    float16 = "float16"


class Input(BaseModel):
    """
    Expected input tensor spec. The ONNX graph itself encodes shape; this section is the deployment-time documentation of what the model assumes, used for sanity-checking incoming data before dispatch.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    ONNX input tensor name (e.g., 'signal'). Matches the ONNX graph's input.
    """
    shape: list[int | str]
    """
    Tensor shape. Integer for fixed dims, '?' (string) for dynamic dims (typically the batch axis). Example for a 1D 1-channel single-trace model: ['?', 1, 512].
    """
    dtype: Dtype
    """
    Input element dtype.
    """


class Output(BaseModel):
    """
    Expected output tensor spec.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    ONNX output tensor name (e.g., 'logit').
    """
    shape: list[int | str]
    """
    Output tensor shape. Example for a single-logit binary classifier: ['?', 1].
    """
    dtype: Dtype
    """
    Output element dtype.
    """
    semantics: Semantics
    """
    What the output value means. 'binary_logit' means apply sigmoid to get P(positive); 'binary_probability' means the value is already sigmoid-applied. Multi-class variants are equivalent for softmax/log-softmax outputs.
    """


class EgmClassModelMetadata(BaseModel):
    """
    Preprocessing + inference-time constants paired with a deployed EGM-classifier model artifact (typically the ONNX file). Captures everything the runtime needs that is NOT encoded in the ONNX graph itself: expected sample rate, expected trace length, per-channel normalization, decision threshold, model artifact hash, training provenance. Cross-language: consumed by Python (training-eval parity) and C++ (TensorRT inference). Schema version 1.0. Renamed from 'model_metadata' at egm-contracts v0.3.0 — the field shape here (binary_logit semantics, 1-channel bandpass, [B, 1, T] input) is specific to the 1D EGM-classifier family. Future model topologies (2D electrode grids, sparse 3D electrode point clouds) get their own schemas.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Versioned schema identifier. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp at export time.
    """
    model_artifact: ModelArtifact
    """
    Reference to the model file this metadata pairs with. Lives next to the artifact on disk (e.g., 'best.onnx' + 'best.model_metadata.json').
    """
    input: Input
    """
    Expected input tensor spec. The ONNX graph itself encodes shape; this section is the deployment-time documentation of what the model assumes, used for sanity-checking incoming data before dispatch.
    """
    output: Output
    """
    Expected output tensor spec.
    """
    preprocessing: Preprocessing
    """
    Signal-conditioning constants the runtime applies before inference, in the order listed here. Must match the preprocessing used during training; mismatch will silently degrade performance.
    """
    decision: Decision
    """
    Decision-rule constants applied to the model output to produce a class label.
    """
    training_provenance: dict[str, Any]
    """
    Where this model came from. Well-known keys: 'run_id' (identifier into the run.json that documents the training), 'run_json_path' (path to the run.json), 'training_bank_path' (path to the synthetic bank used for training), 'training_bank_schema_version' (the synthetic_bank schema version this bank conforms to, e.g. '1.0'), 'git_sha' (source repo state at training time). Additional keys are allowed for producer-specific provenance.
    """
