# generated by datamodel-codegen:
#   filename:  figure_spec.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """

    field_1 = "1"


class Format(Enum):
    """
    Output format. Vector PDF is the default for paper figures.
    """

    pdf = "pdf"
    png = "png"
    svg = "svg"


class Output(BaseModel):
    """
    Where + how the rendered figure is written.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Format
    """
    Output format. Vector PDF is the default for paper figures.
    """
    path: str
    """
    Output path for the rendered image, typically pointing OUT of the meta repo into the paper repo. Gitignored at the destination; regenerated at paper-build time.
    """


class ArtifactId(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode: the Phase-1.5 Wave-1 schema migration writes banks before the splitters populate it, so absence is valid; producers enforce presence once they emit it.
    """


class Group(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    Human-readable group label shown in the legend.
    """
    bank_id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable id of the bank supplying this group's data.
    """


class Inputs(BaseModel):
    """
    Recipe-specific inputs. Permissive (additionalProperties true) because the schema discriminates on `recipe` at the egm-studio layer. Well-known key: `groups` (array of {name, bank_id}) for overlay-style recipes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    groups: list[Group] | None = None
    """
    Named data groups for overlay/comparison recipes.
    """


class FigureSpec(BaseModel):
    """
    Declarative spec for one publication figure, living at intracardiac-platform/project/phases/phase_X/figure_specs/<id>.json. Schema version 1. The spec file is the git-tracked source of truth; the rendered image (output.path, pointing into the paper repo) is gitignored build output regenerated by egm-studio's headless figure-render CLI. The required `description` records why the figure exists so a forgotten figure can be re-evaluated (keep / discard) without re-deriving its purpose. `recipe` names one of egm-studio's figure recipes; recipe-specific fields live under `inputs` (kept permissive here because the recipe vocabulary is owned by egm-studio, not hardcoded into the contract). The figure does not declare which phase it belongs to — that membership is recorded by the phase manifest that points at it. See cross_artifact_linkage_design.md section 5.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """
    id: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure id, fig_ prefix (e.g. fig_feature_distributions_synth_vs_iafdb).
    """
    description: str
    """
    REQUIRED human-readable explanation of what this figure shows and why it was generated. Ensures a figure that was made and then forgotten can be revisited, understood, and either used or discarded.
    """
    recipe: str
    """
    Name of the egm-studio figure recipe that renders this figure (e.g. 'feature-distribution-overlay'). Free-form string: the recipe vocabulary is owned + validated by egm-studio, not enumerated in the contract.
    """
    inputs: Inputs | None = None
    """
    Recipe-specific inputs. Permissive (additionalProperties true) because the schema discriminates on `recipe` at the egm-studio layer. Well-known key: `groups` (array of {name, bank_id}) for overlay-style recipes.
    """
    layout: dict[str, Any] | None = None
    """
    Recipe-specific layout (panel grid, per-panel size, ...). Permissive.
    """
    styling: dict[str, Any] | None = None
    """
    Recipe-specific styling (palette, font, dpi, ...). Permissive.
    """
    output: Output
    """
    Where + how the rendered figure is written.
    """
    illustrates_observations: list[ArtifactId] | None = None
    """
    OPTIONAL observation ids this figure illustrates. Drives the manifest entry's consumes_observations field. Optional because not every figure illustrates a specific observation.
    """
