# generated by datamodel-codegen:
#   filename:  figure_spec.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """

    field_1 = "1"


class Format(Enum):
    """
    Output format. Vector PDF is the default for paper figures.
    """

    pdf = "pdf"
    png = "png"
    svg = "svg"


class Output(BaseModel):
    """
    Where + how the rendered figure is written.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    format: Format
    """
    Output format. Vector PDF is the default for paper figures.
    """
    path: str
    """
    Output path for the rendered image, typically pointing OUT of the meta repo into the paper repo. Gitignored at the destination; regenerated at paper-build time.
    """


class ArtifactId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$")
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>_<YYYY-MM-DD>[_vN]. Role prefixes (tbank_ / lpred_ / upred_ / ptbank_ / nbank_ / run_ / model_ / obs_) encode the artifact's role in the ML pipeline, not its data origin. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class Group(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    """
    Human-readable group label shown in the legend.
    """
    bank_id: str = Field(
        ..., pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$"
    )
    """
    Stable id of the bank supplying this group's data.
    """


class Inputs(BaseModel):
    """
    Recipe-specific inputs. Permissive (additionalProperties true) because the schema discriminates on `recipe` at the egm-studio layer. Well-known key: `groups` (array of {name, bank_id}) for overlay-style recipes.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    groups: list[Group] | None = None
    """
    Named data groups for overlay/comparison recipes.
    """


class FigureSpec(BaseModel):
    """
    Declarative spec for one publication figure, living at intracardiac-platform/project/phases/phase_X/figure_specs/<id>.json. Schema version 1. The spec file is the git-tracked source of truth; the rendered image (output.path, pointing into the paper repo) is gitignored build output regenerated by egm-studio's headless figure-render CLI. The required `description` records why the figure exists so a forgotten figure can be re-evaluated (keep / discard) without re-deriving its purpose. `recipe` names one of egm-studio's figure recipes; recipe-specific fields live under `inputs` (kept permissive here because the recipe vocabulary is owned by egm-studio, not hardcoded into the contract). The figure does not declare which phase it belongs to — that membership is recorded by the phase manifest that points at it. See cross_artifact_linkage_design.md section 5.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """
    id: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure id, fig_ prefix (e.g. fig_feature_distributions_synth_vs_iafdb).
    """
    description: str
    """
    REQUIRED human-readable explanation of what this figure shows and why it was generated. Ensures a figure that was made and then forgotten can be revisited, understood, and either used or discarded.
    """
    recipe: str
    """
    Name of the egm-studio figure recipe that renders this figure (e.g. 'feature-distribution-overlay'). Free-form string: the recipe vocabulary is owned + validated by egm-studio, not enumerated in the contract.
    """
    inputs: Inputs | None = None
    """
    Recipe-specific inputs. Permissive (additionalProperties true) because the schema discriminates on `recipe` at the egm-studio layer. Well-known key: `groups` (array of {name, bank_id}) for overlay-style recipes.
    """
    layout: dict[str, Any] | None = None
    """
    Recipe-specific layout (panel grid, per-panel size, ...). Permissive.
    """
    styling: dict[str, Any] | None = None
    """
    Recipe-specific styling (palette, font, dpi, ...). Permissive.
    """
    output: Output
    """
    Where + how the rendered figure is written.
    """
    illustrates_observations: list[ArtifactId] | None = None
    """
    OPTIONAL observation ids this figure illustrates. Drives the manifest entry's consumes_observations field. Optional because not every figure illustrates a specific observation.
    """
