# generated by datamodel-codegen:
#   filename:  iafdb_bank.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """

    field_1_0 = "1.0"


class Source(Enum):
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """

    iafdb_v1_0_0 = "iafdb v1.0.0"


class FsHz(Enum):
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """

    number_1000_0 = 1000.0


class CalibrationMethod(Enum):
    """
    How per-record amplitude calibration was computed. R-wave anchoring is always applied regardless of threshold strategy. Phase 1 only supports this one method; future methods would add new enum values rather than replacing this one.
    """

    r_wave_anchoring = "r_wave_anchoring"


class ThresholdMode(Enum):
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap; 'percentile' = per-record percentile of the calibrated p-p distribution.
    """

    absolute = "absolute"
    percentile = "percentile"


class BandHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)


class PatientIdItem(RootModel[str]):
    root: str = Field(..., pattern="^iaf[1-8]$")


class StartSampleItem(RootModel[int]):
    root: int = Field(..., ge=0)


class PeakToPeakMvItem(RootModel[float]):
    root: float = Field(..., ge=0.0)


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, window_samples) float32 — calibrated + band-pass-filtered bipolar EGM segments.
    """
    patient_id: list[PatientIdItem]
    """
    (N,) UTF-8 — IAFDB patient identifier, one of 'iaf1'..'iaf8'.
    """
    source_record: list[str]
    """
    (N,) UTF-8 — IAFDB record name (e.g., 'iaf1_afw').
    """
    source_channel: list[str]
    """
    (N,) UTF-8 — Bipolar channel name within the source record (e.g., 'CS12').
    """
    start_sample: list[StartSampleItem]
    """
    (N,) int64 — Sample offset of the segment into the source record. Combined with patient_id + source_record + window_samples, this uniquely identifies the trace's location in the raw IAFDB data.
    """
    peak_to_peak_mv: list[PeakToPeakMvItem]
    """
    (N,) float32 — Calibrated peak-to-peak amplitude in mV that passed the threshold check. Real-mV interpretation.
    """
    calibration_scalar: list[float]
    """
    (N,) float32 — Per-patient scalar applied to this segment during R-wave anchoring. signal_in_mv = signal_raw * calibration_scalar.
    """


class IafdbBank(BaseModel):
    """
    Calibrated + band-pass-filtered bipolar EGM segments extracted from PhysioNet IAFDB. Schema version 1.0. Symmetric with SyntheticBank: maps to an HDF5 file with bank-level root attrs plus a `traces/` group containing per-trace columns. No `label` column — labeling is downstream policy applied at ClassifierBank conversion time by a consumer-supplied label_fn.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    source: Source
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """
    fs_hz: FsHz
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """
    trace_duration_ms: float = Field(..., gt=0.0)
    """
    Per-trace duration in milliseconds (equals window_ms).
    """
    calibration_method: CalibrationMethod
    """
    How per-record amplitude calibration was computed. R-wave anchoring is always applied regardless of threshold strategy. Phase 1 only supports this one method; future methods would add new enum values rather than replacing this one.
    """
    calibration_target_qrs_pp_mv: float = Field(..., gt=0.0)
    """
    Target peak-to-peak QRS amplitude in mV against which each record was calibrated.
    """
    threshold_mode: ThresholdMode
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap; 'percentile' = per-record percentile of the calibrated p-p distribution.
    """
    threshold_value: float
    """
    Value used by the threshold strategy. mV for 'absolute' (e.g., 0.5 per Sánchez); 0..100 percentile for 'percentile'.
    """
    band_hz: list[BandHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz, [low, high]. Defaults to the clinical 30-300 Hz band.
    """
    window_ms: float = Field(..., gt=0.0)
    """
    Sliding-window length in ms. Default 512 ms to match the classifier's T=512 input.
    """
    window_samples: int = Field(..., gt=0)
    """
    Window length in samples (= window_ms * 1e-3 * fs_hz).
    """
    hop_ms: float | None = Field(None, gt=0.0)
    """
    Stride between adjacent windows in ms. Additive (not in the original format-version-1 spec but recorded for reproducibility; readers MAY ignore it).
    """
    source_records: list[str]
    """
    Record names that contributed at least one segment to this bank (e.g., 'iaf1_afw'). Allows zero entries (empty bank is valid).
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """
