# generated by datamodel-codegen:
#   filename:  iafdb_bank.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions. 1.1 (from 1.0) added: 'none' to threshold_mode enum + nullable threshold_value, for the unfiltered-export path (every window, no healthy threshold). 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). Pre-1.0 of egm-contracts: enum-of-one pattern per project/schema_evolution.md (no in-the-wild back-compat needed yet); when v1.0 ships, this enum may grow to accept multiple supported versions.
    """

    field_1_2 = "1.2"


class Source(Enum):
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """

    iafdb_v1_0_0 = "iafdb v1.0.0"


class FsHz(Enum):
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """

    number_1000_0 = 1000.0


class CalibrationMethod(Enum):
    """
    How per-record amplitude calibration was computed. R-wave anchoring is always applied regardless of threshold strategy. Phase 1 only supports this one method; future methods would add new enum values rather than replacing this one.
    """

    r_wave_anchoring = "r_wave_anchoring"


class ThresholdMode(Enum):
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap (default 0.5 per Sánchez 2000, or 0.2 per Kosiuk AF-adjusted); 'percentile' = per-record percentile of the calibrated p-p distribution; 'none' (since 1.1) = no filter applied, every windowed segment retained — used for unsupervised pretraining banks where label semantics don't gate selection.
    """

    absolute = "absolute"
    percentile = "percentile"
    none = "none"


class BandHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)


class PatientIdItem(RootModel[str]):
    root: str = Field(..., pattern="^iaf[1-8]$")


class StartSampleItem(RootModel[int]):
    root: int = Field(..., ge=0)


class PeakToPeakMvItem(RootModel[float]):
    root: float = Field(..., ge=0.0)


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, window_samples) float32 — calibrated + band-pass-filtered bipolar EGM segments.
    """
    patient_id: list[PatientIdItem]
    """
    (N,) UTF-8 — IAFDB patient identifier, one of 'iaf1'..'iaf8'.
    """
    source_record: list[str]
    """
    (N,) UTF-8 — IAFDB record name (e.g., 'iaf1_afw').
    """
    source_channel: list[str]
    """
    (N,) UTF-8 — Bipolar channel name within the source record (e.g., 'CS12').
    """
    start_sample: list[StartSampleItem]
    """
    (N,) int64 — Sample offset of the segment into the source record. Combined with patient_id + source_record + window_samples, this uniquely identifies the trace's location in the raw IAFDB data.
    """
    peak_to_peak_mv: list[PeakToPeakMvItem]
    """
    (N,) float32 — Calibrated peak-to-peak amplitude in mV that passed the threshold check. Real-mV interpretation.
    """
    calibration_scalar: list[float]
    """
    (N,) float32 — Per-patient scalar applied to this segment during R-wave anchoring. signal_in_mv = signal_raw * calibration_scalar.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode: the Phase-1.5 Wave-1 schema migration writes banks before the splitters populate it, so absence is valid; producers enforce presence once they emit it.
    """


class IafdbBank(BaseModel):
    """
    Calibrated + band-pass-filtered bipolar EGM segments extracted from PhysioNet IAFDB. Schema version 1.2. Symmetric with SyntheticBank: maps to an HDF5 file with bank-level root attrs plus a `traces/` group containing per-trace columns. No `label` column — labeling is downstream policy applied at ClassifierBank conversion time by a consumer-supplied label_fn. 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions. 1.1 (from 1.0) added: 'none' to threshold_mode enum + nullable threshold_value, for the unfiltered-export path (every window, no healthy threshold). 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). Pre-1.0 of egm-contracts: enum-of-one pattern per project/schema_evolution.md (no in-the-wild back-compat needed yet); when v1.0 ships, this enum may grow to accept multiple supported versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    bank_id: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID for this bank, e.g. 'upred_iafdb_v1_5_2026-06-25' or 'nbank_iafdb_2026-06-15'. Optional for legacy banks written before egm-contracts v0.5.0; egm-data stamps it on every new bank (enforced at write time, not by this schema). Added 1.2.
    """
    source: Source
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """
    fs_hz: FsHz
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """
    trace_duration_ms: float = Field(..., gt=0.0)
    """
    Per-trace duration in milliseconds (equals window_ms).
    """
    calibration_method: CalibrationMethod
    """
    How per-record amplitude calibration was computed. R-wave anchoring is always applied regardless of threshold strategy. Phase 1 only supports this one method; future methods would add new enum values rather than replacing this one.
    """
    calibration_target_qrs_pp_mv: float = Field(..., gt=0.0)
    """
    Target peak-to-peak QRS amplitude in mV against which each record was calibrated.
    """
    threshold_mode: ThresholdMode
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap (default 0.5 per Sánchez 2000, or 0.2 per Kosiuk AF-adjusted); 'percentile' = per-record percentile of the calibrated p-p distribution; 'none' (since 1.1) = no filter applied, every windowed segment retained — used for unsupervised pretraining banks where label semantics don't gate selection.
    """
    threshold_value: float | None
    """
    Value used by the threshold strategy. mV for 'absolute' (e.g., 0.5 per Sánchez); 0..100 percentile for 'percentile'; null when threshold_mode='none' (since 1.1).
    """
    band_hz: list[BandHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz, [low, high]. Defaults to the clinical 30-300 Hz band.
    """
    window_ms: float = Field(..., gt=0.0)
    """
    Sliding-window length in ms. Default 512 ms to match the classifier's T=512 input.
    """
    window_samples: int = Field(..., gt=0)
    """
    Window length in samples (= window_ms * 1e-3 * fs_hz).
    """
    hop_ms: float | None = Field(None, gt=0.0)
    """
    Stride between adjacent windows in ms. Additive (not in the original format-version-1 spec but recorded for reproducibility; readers MAY ignore it).
    """
    source_records: list[str]
    """
    Record names that contributed at least one segment to this bank (e.g., 'iaf1_afw'). Allows zero entries (empty bank is valid).
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """
