# generated by datamodel-codegen:
#   filename:  iafdb_bank.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions. 1.1 (from 1.0) added: 'none' to threshold_mode enum + nullable threshold_value, for the unfiltered-export path (every window, no healthy threshold). 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). 1.3 (from 1.2) added the optional `run_record_path` sidecar pointer + the optional per-trace `activation_position` (egm-contracts v0.6.0). 1.4 (from 1.3) widened `calibration_method` to admit 'none'. ORDER IS LOAD-BEARING: schema_info.current_version() returns the LAST entry, so '1.4' must stay last or new banks would be stamped with the older version. Pre-1.0 of egm-contracts: the enum-of-one pattern per project/schema_evolution.md (no in-the-wild back-compat needed yet); when v1.0 ships, this enum may grow to accept multiple supported versions.
    """

    field_1_3 = "1.3"
    field_1_4 = "1.4"


class Source(Enum):
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """

    iafdb_v1_0_0 = "iafdb v1.0.0"


class FsHz(Enum):
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """

    number_1000_0 = 1000.0


class CalibrationMethod(Enum):
    """
    How per-record amplitude calibration was computed, or 'none' when no calibration was applied and the stored signal is in the source dataset's raw units. 'none' was added in 1.4 because a single-member enum left an uncalibrated bank with no legal value to write — the only value that validated asserted a calibration step had run when it had not, so the file itself would have carried a false claim about its own signal processing. That is the line: a field that would merely be unused can take a sentinel, a field that would be untrue cannot. Which method is appropriate is a scientific question settled per corpus rather than a schema default — R-wave anchoring scales EGM amplitude against a surface-ECG QRS reference, which is not standard intracardiac practice, so it is a selectable option and not the forced path. Future methods add enum values rather than replacing existing ones.
    """

    r_wave_anchoring = "r_wave_anchoring"
    none = "none"


class ThresholdMode(Enum):
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap (default 0.5 per Sánchez 2000, or 0.2 per Kosiuk AF-adjusted); 'percentile' = per-record percentile of the calibrated p-p distribution; 'none' (since 1.1) = no filter applied, every windowed segment retained — used for unsupervised pretraining banks where label semantics don't gate selection.
    """

    absolute = "absolute"
    percentile = "percentile"
    none = "none"


class BandHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)


class PatientIdItem(RootModel[str]):
    root: str = Field(..., pattern="^iaf[1-8]$")


class StartSampleItem(RootModel[int]):
    root: int = Field(..., ge=0)


class PeakToPeakMvItem(RootModel[float]):
    root: float = Field(..., ge=0.0)


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode, and PERMANENTLY so - the field is meaningful only for single-activation traces. It is absent whenever no single anchor exists: sliding-window extraction (no activation anchor at all), multi-beat traces (several activations, so no one position describes the trace), and any bank written before its producer's splitter shipped. Consumers MUST treat absence as 'unknown position' - never as 0.0, which is a legitimate value meaning the activation sits on the first sample, so defaulting would fabricate a spike at the low edge of the distribution.
    """


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, window_samples) float32 — calibrated + band-pass-filtered bipolar EGM segments.
    """
    patient_id: list[PatientIdItem]
    """
    (N,) UTF-8 — IAFDB patient identifier, one of 'iaf1'..'iaf8'.
    """
    source_record: list[str]
    """
    (N,) UTF-8 — IAFDB record name (e.g., 'iaf1_afw').
    """
    source_channel: list[str]
    """
    (N,) UTF-8 — Bipolar channel name within the source record (e.g., 'CS12').
    """
    start_sample: list[StartSampleItem]
    """
    (N,) int64 — Sample offset of the segment into the source record. Combined with patient_id + source_record + window_samples, this uniquely identifies the trace's location in the raw IAFDB data.
    """
    peak_to_peak_mv: list[PeakToPeakMvItem]
    """
    (N,) float32 — Calibrated peak-to-peak amplitude in mV that passed the threshold check. Real-mV interpretation.
    """
    calibration_scalar: list[float]
    """
    (N,) float32 — Per-patient scalar applied to this segment during R-wave anchoring. signal_in_mv = signal_raw * calibration_scalar.
    """
    activation_position: list[ActivationPosition] | None = None
    """
    (N,) float32 — Realized activation position within each window, as a [0,1] fraction of the trace (see common.schema.json ActivationPosition for the convention). Written by the activation-aware splitter, which anchors each window on a detected activation; it is what the splitter PRODUCED, not a measurement taken from the waveform afterwards. OPTIONAL, and permanently so — see common.ActivationPosition for the full rule. Absent on sliding-window banks (no anchor exists), on multi-beat traces (no single position describes them), and on activation-mode banks written before the splitter shipped: Phase-1.5 Wave 1 adds this column, Wave 2 (IAF1) populates it. Readers MUST treat absence as 'unknown position', not zero. Its counterpart on synthetic_bank carries the identical definition so the two corpora's position distributions are compared stored-vs-stored. Added 1.3.
    """


class IafdbBank(BaseModel):
    """
    Calibrated + band-pass-filtered bipolar EGM segments extracted from PhysioNet IAFDB. Schema versions 1.3-1.4 (new banks are stamped 1.4). Symmetric with SyntheticBank: maps to an HDF5 file with bank-level root attrs plus a `traces/` group containing per-trace columns. No `label` column — labeling is downstream policy applied at ClassifierBank conversion time by a consumer-supplied label_fn. 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). 1.3 (from 1.2) added the optional `run_record_path` sidecar pointer and the optional per-trace `activation_position` (egm-contracts v0.6.0, Phase 1.5). 1.4 (from 1.3) widened `calibration_method` to admit 'none' so a bank that was not calibrated can say so instead of asserting a step that never ran (egm-contracts v0.6.1). Both versions are accepted on read.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions. 1.1 (from 1.0) added: 'none' to threshold_mode enum + nullable threshold_value, for the unfiltered-export path (every window, no healthy threshold). 1.2 (from 1.1) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage). 1.3 (from 1.2) added the optional `run_record_path` sidecar pointer + the optional per-trace `activation_position` (egm-contracts v0.6.0). 1.4 (from 1.3) widened `calibration_method` to admit 'none'. ORDER IS LOAD-BEARING: schema_info.current_version() returns the LAST entry, so '1.4' must stay last or new banks would be stamped with the older version. Pre-1.0 of egm-contracts: the enum-of-one pattern per project/schema_evolution.md (no in-the-wild back-compat needed yet); when v1.0 ships, this enum may grow to accept multiple supported versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    bank_id: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID for this bank, e.g. 'upred_iafdb_v1_5_2026-06-25' or 'nbank_iafdb_2026-06-15'. Optional for legacy banks written before egm-contracts v0.5.0; egm-data stamps it on every new bank (enforced at write time, not by this schema). Added 1.2.
    """
    run_record_path: str | None = None
    """
    Relative path to a sibling JSON run record holding this bank's per-record extraction diagnostics, e.g. 'iafdb_healthy_v1_run_record.json'. Relative to the bank file's own directory, mirroring the noise_bank <-> noise_bank_run_record sibling convention. Optional: a bank written without the audit report simply omits it, and readers MUST treat absence as 'no sidecar', not as an error. The record's own schema is deliberately NOT formalized yet (the methods paper may reshape it); until it is, the file is documented-but-unvalidated JSON, which is why this is a path rather than an embedded object. Added 1.3.
    """
    source: Source
    """
    Provenance tag identifying the upstream dataset. Bumps when the underlying PhysioNet dataset version changes.
    """
    fs_hz: FsHz
    """
    Sampling rate in Hz. IAFDB is fixed at 1 kHz; enum (rather than const) so datamodel-code-generator emits a Literal[1000.0] in Pydantic and a concrete typed enum in C++. The exclusiveMinimum belt-and-suspenders catches malformed values that bypass the enum check.
    """
    trace_duration_ms: float = Field(..., gt=0.0)
    """
    Per-trace duration in milliseconds (equals window_ms).
    """
    calibration_method: CalibrationMethod
    """
    How per-record amplitude calibration was computed, or 'none' when no calibration was applied and the stored signal is in the source dataset's raw units. 'none' was added in 1.4 because a single-member enum left an uncalibrated bank with no legal value to write — the only value that validated asserted a calibration step had run when it had not, so the file itself would have carried a false claim about its own signal processing. That is the line: a field that would merely be unused can take a sentinel, a field that would be untrue cannot. Which method is appropriate is a scientific question settled per corpus rather than a schema default — R-wave anchoring scales EGM amplitude against a surface-ECG QRS reference, which is not standard intracardiac practice, so it is a selectable option and not the forced path. Future methods add enum values rather than replacing existing ones.
    """
    calibration_target_qrs_pp_mv: float = Field(..., gt=0.0)
    """
    Target peak-to-peak QRS amplitude in mV against which each record was calibrated. Stays REQUIRED and strictly positive even when calibration_method is 'none': producers write +inf, the same sentinel convention peak_to_peak_mv and hop_ms already use for not-applicable-in-this-mode. Deliberately not made nullable — a sentinel in a field that is merely unused costs nothing, while nullable would force every reader to handle a None it can never act on.
    """
    threshold_mode: ThresholdMode
    """
    Threshold strategy that decided which segments are retained. 'absolute' = fixed mV cap (default 0.5 per Sánchez 2000, or 0.2 per Kosiuk AF-adjusted); 'percentile' = per-record percentile of the calibrated p-p distribution; 'none' (since 1.1) = no filter applied, every windowed segment retained — used for unsupervised pretraining banks where label semantics don't gate selection.
    """
    threshold_value: float | None
    """
    Value used by the threshold strategy. mV for 'absolute' (e.g., 0.5 per Sánchez); 0..100 percentile for 'percentile'; null when threshold_mode='none' (since 1.1).
    """
    band_hz: list[BandHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz, [low, high]. Defaults to the clinical 30-300 Hz band.
    """
    window_ms: float = Field(..., gt=0.0)
    """
    Sliding-window length in ms. Default 512 ms to match the classifier's T=512 input.
    """
    window_samples: int = Field(..., gt=0)
    """
    Window length in samples (= window_ms * 1e-3 * fs_hz).
    """
    hop_ms: float | None = Field(None, gt=0.0)
    """
    Stride between adjacent windows in ms. Additive (not in the original format-version-1 spec but recorded for reproducibility; readers MAY ignore it).
    """
    source_records: list[str]
    """
    Record names that contributed at least one segment to this bank (e.g., 'iaf1_afw'). Allows zero entries (empty bank is valid).
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """
