# generated by datamodel-codegen:
#   filename:  metrics.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class MetricsRow(BaseModel):
    """
    Flat per-epoch training metrics, one row per epoch in metrics.csv. Column order is the contract (consumers read by header name, but plot/spreadsheet defaults assume this order). The CSV writes empty cells for non-finite values; the JSON representation of a row treats those as null. Schema describes one row. Validity rule: epoch / lr / train_loss / val_loss / epoch_seconds are always present and finite — if a producer writes them as null/empty, that's a producer bug worth surfacing. Validation metrics (val_auroc / val_accuracy / etc.) are legitimately nullable: AUROC is undefined on a single-class val split, ECE is undefined when no reliability bin contains samples, etc.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    epoch: int = Field(..., ge=1)
    """
    1-based epoch number. Strictly increasing across the run.
    """
    lr: float = Field(..., ge=0.0)
    """
    Learning rate at the epoch's last optimizer step. Required and finite — captures schedule behavior.
    """
    train_loss: float
    """
    Mean training-set loss across all batches in the epoch. Required and finite.
    """
    val_loss: float
    """
    Mean validation-set loss across all batches in the epoch. Required and finite. (Validation-set selection lives in the run config, not here.)
    """
    val_auroc: float | None = Field(None, ge=0.0, le=1.0)
    """
    Validation AUROC for the positive class. Null when AUROC is undefined (e.g., a single-class val split, or zero positives).
    """
    val_accuracy: float | None = Field(None, ge=0.0, le=1.0)
    """
    Validation accuracy at the configured decision threshold (typically 0.5). Null when the val set is empty.
    """
    val_precision: float | None = Field(None, ge=0.0, le=1.0)
    """
    Validation precision = TP / (TP + FP). Null when TP + FP == 0 (no positives predicted).
    """
    val_recall: float | None = Field(None, ge=0.0, le=1.0)
    """
    Validation recall = TP / (TP + FN). Null when TP + FN == 0 (no actual positives in val set).
    """
    val_f1: float | None = Field(None, ge=0.0, le=1.0)
    """
    Validation F1 = harmonic mean of precision and recall. Null when either precision or recall is null.
    """
    val_ece: float | None = Field(None, ge=0.0)
    """
    Expected Calibration Error: weighted average gap between predicted confidence and empirical accuracy across reliability bins. Lower is better-calibrated. Null when no reliability bin contains samples.
    """
    epoch_seconds: float = Field(..., ge=0.0)
    """
    Wall-clock seconds spent on this epoch (training + validation). Required.
    """
