# generated by datamodel-codegen:
#   filename:  noise_bank.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """

    field_1_1 = "1.1"


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, T) float32 — band-pass-filtered bipolar window. The only column the mixer's math reads.
    """
    source_record: list[str]
    """
    (N,) UTF-8 — Source-dataset record identifier (e.g., 'iaf1_afw' for IAFDB). The mixer copies this onto each output trace as an audit field; downstream debugging can trace a hybrid sample back to the source noise.
    """
    source_channel: list[str]
    """
    (N,) UTF-8 — Bipolar channel name within the source record (e.g., 'CS12' for IAFDB). Same audit-propagation role as source_record.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode: the Phase-1.5 Wave-1 schema migration writes banks before the splitters populate it, so absence is valid; producers enforce presence once they emit it.
    """


class NoiseBank(BaseModel):
    """
    Low-amplitude (quiet) bipolar EGM segments used as additive noise by the synthetic-EGM mixer. Schema version 1.1. Intentionally minimal: only the fields the mixer actually consumes are required here. Extraction provenance (calibration scheme, threshold strategy, filter band, per-trace metadata) lives in a sibling noise_bank_run_record.json file. The convention is the same as metrics.csv + run.json in egm-classifier: the two files are written together with matching name stems and the consumer that needs methods opens the sibling. 1.1 (from 1.0) added the optional `bank_id` stable-artifact identifier as a root attr, so a consumer can read the bank's identity from the .h5 itself rather than having to open the sidecar.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    bank_id: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID for this noise bank, e.g. 'nbank_iafdb_2026-06-15'. Optional for legacy banks written before egm-contracts v0.6.0; egm-data stamps it on every new bank (enforced at write time, not by this schema, per the cross-artifact-linkage 'optional-in-schema, required-on-write' decision). The sibling noise_bank_run_record carries the same id (added there in 1.1 / v0.5.0); when both are present they MUST agree — egm-data checks that, since JSON Schema cannot compare across two files. Added 1.1.
    """
    source: str
    """
    Free-form provenance tag identifying the upstream dataset (e.g., 'iafdb v1.0.0'). Producers stamp this; consumers read it to decide whether banks from different sources are mixable. Not an enum so new datasets can show up without a schema bump.
    """
    fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate in Hz. The mixer asserts that this matches the synthetic side's fs and refuses to mix if it doesn't.
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """
