# generated by datamodel-codegen:
#   filename:  noise_bank_run_record.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """

    field_1_1 = "1.1"


class Windowing(BaseModel):
    """
    Sliding-window extraction parameters.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    window_ms: float = Field(..., gt=0.0)
    """
    Window length in milliseconds.
    """
    window_samples: int = Field(..., gt=0)
    """
    Window length in samples. Cross-field invariant: window_samples == round(window_ms * 1e-3 * fs_hz).
    """
    hop_ms: float = Field(..., gt=0.0)
    """
    Stride between adjacent windows in milliseconds.
    """


class BandHzItem(RootModel[float]):
    root: float = Field(..., gt=0.0)


class Calibration(BaseModel):
    """
    How signal amplitude was calibrated before threshold selection.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    method: str
    """
    Calibration scheme. Open string (not enum) so any source's calibration is representable: 'r_wave_anchoring' (IAFDB), 'none' (raw signal pass-through), 'fixed_gain' (PhysioNet header gain only), future methods. When 'none', peak_to_peak_mv in this file is in raw signal units rather than mV.
    """
    target_qrs_pp_mv: float | None
    """
    Target peak-to-peak QRS amplitude in mV against which each source record was calibrated. Null when method has no notion of a target (e.g., 'none' or 'fixed_gain').
    """


class ThresholdMode(Enum):
    """
    Strategy. 'absolute' = keep windows with peak-to-peak ≤ threshold_value mV (requires calibrated input). 'percentile' = keep windows in the bottom threshold_value%% of the pooled per-record p-p distribution (scale-invariant).
    """

    absolute = "absolute"
    percentile = "percentile"


class Selection(BaseModel):
    """
    Threshold strategy used to select quiet windows.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    threshold_mode: ThresholdMode
    """
    Strategy. 'absolute' = keep windows with peak-to-peak ≤ threshold_value mV (requires calibrated input). 'percentile' = keep windows in the bottom threshold_value%% of the pooled per-record p-p distribution (scale-invariant).
    """
    threshold_value: float
    """
    mV for 'absolute'; 0..100 percentile for 'percentile'.
    """


class StartSampleItem(RootModel[int]):
    root: int = Field(..., ge=0)


class PeakToPeakMvItem(RootModel[float]):
    root: float = Field(..., ge=0.0)


class PerTraceProvenance(BaseModel):
    """
    Optional parallel arrays of per-trace audit fields aligned to the bank's traces (index i here corresponds to bank traces row i). Producers SHOULD write this for any bank intended for paper-citable use; smaller test fixtures may omit it. Consumers that need patient-aware sampling or unit-aware mixing read these arrays; the v1 mixer ignores them entirely.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    patient_id: list[str]
    """
    (N,) Source-dataset patient identifier for each trace. No pattern constraint.
    """
    start_sample: list[StartSampleItem]
    """
    (N,) Sample offset of the segment in its source record. Combined with patient_id + the bank's source_record + windowing.window_samples, uniquely identifies the trace's location in the raw source data.
    """
    peak_to_peak_mv: list[PeakToPeakMvItem]
    """
    (N,) Band-passed peak-to-peak amplitude that passed the threshold. Real mV when calibration.method calibrated the input; raw signal units when calibration.method='none'.
    """
    calibration_scalar: list[float]
    """
    (N,) Per-record calibration scalar applied to this segment. signal_in_mv = signal_raw * calibration_scalar. When calibration.method='none' producers SHOULD write 1.0 here so consumers don't accidentally rescale.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode, and PERMANENTLY so - the field is meaningful only for single-activation traces. It is absent whenever no single anchor exists: sliding-window extraction (no activation anchor at all), multi-beat traces (several activations, so no one position describes the trace), and any bank written before its producer's splitter shipped. Consumers MUST treat absence as 'unknown position' - never as 0.0, which is a legitimate value meaning the activation sits on the first sample, so defaulting would fabricate a spike at the low edge of the distribution.
    """


class NoiseBankRunRecord(BaseModel):
    """
    Provenance sidecar for a NoiseBank HDF5 file: how the noise segments were extracted (calibration, threshold strategy, filter band, windowing) plus per-trace provenance arrays aligned to the bank's traces. Schema version 1.1. Written as a sibling JSON file next to the bank with a matching name stem (e.g. iafdb_noise_v1.h5 + iafdb_noise_v1_run_record.json), following the same convention as metrics.csv + run.json in egm-classifier. The mixer never opens this file; debuggers, reproducibility audits, and the white paper's methods section do. 1.1 (from 1.0) added the optional `bank_id` stable-artifact identifier for the noise bank (egm-contracts v0.5.0, cross-artifact linkage); the design puts the noise bank's stable ID on this sidecar rather than the HDF5.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time. Should match (or closely follow) the sibling bank's created_utc.
    """
    bank_id: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID for the noise bank this sidecar describes, e.g. 'nbank_iafdb_2026-06-15'. Optional for legacy records written before egm-contracts v0.5.0; egm-data stamps it on every new noise bank (enforced at write time, not by this schema). Added 1.1.
    """
    source: str
    """
    Free-form provenance tag for the upstream dataset, identical to the sibling bank's source field. Producers stamp the same value in both files.
    """
    description: str | None = None
    """
    Free-form human-readable note about how this bank was built — strategy params, dataset slice, anything that helps a reader reproduce or understand the run. Default empty.
    """
    fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate in Hz. Mirrors the sibling bank's fs_hz; carried here so the run record stands alone as documentation.
    """
    windowing: Windowing
    """
    Sliding-window extraction parameters.
    """
    band_hz: list[BandHzItem] = Field(..., max_length=2, min_length=2)
    """
    Band-pass filter edges in Hz, [low, high], applied before peak-to-peak computation. Defaults to the clinical 30-300 Hz bipolar EGM band so noise is characterised in the same band the classifier sees.
    """
    calibration: Calibration
    """
    How signal amplitude was calibrated before threshold selection.
    """
    selection: Selection
    """
    Threshold strategy used to select quiet windows.
    """
    source_records: list[str]
    """
    Record names from the upstream dataset that contributed at least one segment to the bank (e.g., 'iaf1_afw'). Allows zero entries (empty bank is valid).
    """
    per_trace_provenance: PerTraceProvenance | None = None
    """
    Optional parallel arrays of per-trace audit fields aligned to the bank's traces (index i here corresponds to bank traces row i). Producers SHOULD write this for any bank intended for paper-citable use; smaller test fixtures may omit it. Consumers that need patient-aware sampling or unit-aware mixing read these arrays; the v1 mixer ignores them entirely.
    """
