# generated by datamodel-codegen:
#   filename:  noise_bank.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """

    field_1_0 = "1.0"


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, T) float32 — band-pass-filtered bipolar window. The only column the mixer's math reads.
    """
    source_record: list[str]
    """
    (N,) UTF-8 — Source-dataset record identifier (e.g., 'iaf1_afw' for IAFDB). The mixer copies this onto each output trace as an audit field; downstream debugging can trace a hybrid sample back to the source noise.
    """
    source_channel: list[str]
    """
    (N,) UTF-8 — Bipolar channel name within the source record (e.g., 'CS12' for IAFDB). Same audit-propagation role as source_record.
    """


class NoiseBank(BaseModel):
    """
    Low-amplitude (quiet) bipolar EGM segments used as additive noise by the synthetic-EGM mixer. Schema version 1.0. Intentionally minimal: only the fields the mixer actually consumes are required here. Extraction provenance (calibration scheme, threshold strategy, filter band, per-trace metadata) lives in a sibling noise_bank_run_record.json file. The convention is the same as metrics.csv + run.json in egm-classifier: the two files are written together with matching name stems and the consumer that needs methods opens the sibling.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    source: str
    """
    Free-form provenance tag identifying the upstream dataset (e.g., 'iafdb v1.0.0'). Producers stamp this; consumers read it to decide whether banks from different sources are mixable. Not an enum so new datasets can show up without a schema bump.
    """
    fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate in Hz. The mixer asserts that this matches the synthetic side's fs and refuses to mix if it doesn't.
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the segment count) and are aligned.
    """
