# generated by datamodel-codegen:
#   filename:  observation.schema.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """

    field_1 = "1"


class SelectedTraceIndicesWithinFilterItem(RootModel[int]):
    root: int = Field(..., ge=0)


class ArtifactId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$")
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>_<YYYY-MM-DD>[_vN]. Role prefixes (tbank_ / lpred_ / upred_ / ptbank_ / nbank_ / run_ / model_ / obs_) encode the artifact's role in the ML pipeline, not its data origin. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class TraceRef(BaseModel):
    """
    Reference to one trace inside a bank. v0.1 trace addressing is (bank id, integer index); stable per-trace IDs are a deferred upgrade.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bank: str = Field(..., pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$")
    """
    Stable id of the bank the trace lives in.
    """
    index: int = Field(..., ge=0)
    """
    Integer index of the trace within the bank (v0.1 trace ID).
    """


class References(BaseModel):
    """
    Structured references to OTHER artifact types (models, parent observations). Bank refs are intentionally absent here — they are derived from view_state.banks_loaded + traces[].bank.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[ArtifactId] | None = None
    """
    Models this observation is about, if any.
    """
    observations: list[ArtifactId] | None = None
    """
    Parent observations this one builds on, if any.
    """


class ViewState(BaseModel):
    """
    OPTIONAL egm-studio reload state — what to load to recreate the view that produced this observation. egm-studio owns the exact shape; additional keys are allowed for forward compatibility.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    banks_loaded: list[ArtifactId] | None = None
    """
    Bank IDs loaded in the view.
    """
    filter: str | None = None
    """
    Filter expression applied (e.g. 'sample_entropy > 1.5').
    """
    sort: str | None = None
    """
    Sort expression applied (e.g. 'sample_entropy desc').
    """
    selected_trace_indices_within_filter: (
        list[SelectedTraceIndicesWithinFilterItem] | None
    ) = None
    """
    Indices selected within the filtered/sorted view.
    """


class Observation(BaseModel):
    """
    A recorded discovery made during signal exploration or ML diagnostics, living at intracardiac-platform/project/phases/phase_X/observations/<id>.json. Schema version 1. The free-text `description` is REQUIRED — the discovery IS the observation; a pure trace list with no prose is data without context. `traces` (pinned traces of interest) and `view_state` (egm-studio reload state) are OPTIONAL. Bank references are DERIVED (by validate_manifest) from the union of view_state.banks_loaded and traces[].bank, never declared separately, so they can't go out of sync. The observation does not declare which phase it belongs to — that membership is recorded by the phase manifest that points at it. See cross_artifact_linkage_design.md section 4.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """
    id: str = Field(..., pattern="^[a-z]+_[a-z0-9_]+_\\d{4}-\\d{2}-\\d{2}(_v\\d+)?$")
    """
    Stable artifact ID, obs_ prefix (e.g. obs_courtemanche_high_entropy_tail_2026-06-25).
    """
    date: date_aliased
    """
    Date the observation was recorded (YYYY-MM-DD).
    """
    title: str
    """
    One-line summary of the discovery.
    """
    description: str
    """
    REQUIRED free-text prose — the 'what I noticed'. The whole point of an observation; lets someone returning cold understand the finding and decide whether it still matters.
    """
    references: References | None = None
    """
    Structured references to OTHER artifact types (models, parent observations). Bank refs are intentionally absent here — they are derived from view_state.banks_loaded + traces[].bank.
    """
    traces: list[TraceRef] | None = None
    """
    OPTIONAL pinned traces of interest. Becomes the data source for downstream trace-gallery figures that reference this observation.
    """
    view_state: ViewState | None = None
    """
    OPTIONAL egm-studio reload state — what to load to recreate the view that produced this observation. egm-studio owns the exact shape; additional keys are allowed for forward compatibility.
    """
