# generated by datamodel-codegen:
#   filename:  observation.schema.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """

    field_1 = "1"


class SelectedTraceIndicesWithinFilterItem(RootModel[int]):
    root: int = Field(..., ge=0)


class ArtifactId(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode, and PERMANENTLY so - the field is meaningful only for single-activation traces. It is absent whenever no single anchor exists: sliding-window extraction (no activation anchor at all), multi-beat traces (several activations, so no one position describes the trace), and any bank written before its producer's splitter shipped. Consumers MUST treat absence as 'unknown position' - never as 0.0, which is a legitimate value meaning the activation sits on the first sample, so defaulting would fabricate a spike at the low edge of the distribution.
    """


class TraceRef(BaseModel):
    """
    Reference to one trace inside a bank. v0.1 trace addressing is (bank id, integer index); stable per-trace IDs are a deferred upgrade.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    bank: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable id of the bank the trace lives in.
    """
    index: int = Field(..., ge=0)
    """
    Integer index of the trace within the bank (v0.1 trace ID).
    """


class References(BaseModel):
    """
    Structured references to OTHER artifact types (models, parent observations). Bank refs are intentionally absent here — they are derived from view_state.banks_loaded + traces[].bank.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    models: list[ArtifactId] | None = None
    """
    Models this observation is about, if any.
    """
    observations: list[ArtifactId] | None = None
    """
    Parent observations this one builds on, if any.
    """


class ViewState(BaseModel):
    """
    OPTIONAL egm-studio reload state — what to load to recreate the view that produced this observation. egm-studio owns the exact shape; additional keys are allowed for forward compatibility.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    banks_loaded: list[ArtifactId] | None = None
    """
    Bank IDs loaded in the view.
    """
    filter: str | None = None
    """
    Filter expression applied (e.g. 'sample_entropy > 1.5').
    """
    sort: str | None = None
    """
    Sort expression applied (e.g. 'sample_entropy desc').
    """
    selected_trace_indices_within_filter: (
        list[SelectedTraceIndicesWithinFilterItem] | None
    ) = None
    """
    Indices selected within the filtered/sorted view.
    """


class Observation(BaseModel):
    """
    A recorded discovery made during signal exploration or ML diagnostics, living at intracardiac-platform/project/phases/phase_X/observations/<id>.json. Schema version 1. The free-text `description` is REQUIRED — the discovery IS the observation; a pure trace list with no prose is data without context. `traces` (pinned traces of interest) and `view_state` (egm-studio reload state) are OPTIONAL. Bank references are DERIVED (by validate_manifest) from the union of view_state.banks_loaded and traces[].bank, never declared separately, so they can't go out of sync. The observation does not declare which phase it belongs to — that membership is recorded by the phase manifest that points at it. See cross_artifact_linkage_design.md section 4.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version. Consumers MUST refuse unknown major versions.
    """
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID, obs_ prefix (e.g. obs_courtemanche_high_entropy_tail_2026-06-25).
    """
    date: date_aliased
    """
    Date the observation was recorded (YYYY-MM-DD).
    """
    title: str
    """
    One-line summary of the discovery.
    """
    description: str
    """
    REQUIRED free-text prose — the 'what I noticed'. The whole point of an observation; lets someone returning cold understand the finding and decide whether it still matters.
    """
    references: References | None = None
    """
    Structured references to OTHER artifact types (models, parent observations). Bank refs are intentionally absent here — they are derived from view_state.banks_loaded + traces[].bank.
    """
    traces: list[TraceRef] | None = None
    """
    OPTIONAL pinned traces of interest. Becomes the data source for downstream trace-gallery figures that reference this observation.
    """
    view_state: ViewState | None = None
    """
    OPTIONAL egm-studio reload state — what to load to recreate the view that produced this observation. egm-studio owns the exact shape; additional keys are allowed for forward compatibility.
    """
