# generated by datamodel-codegen:
#   filename:  phase_manifest.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version. Consumers MUST refuse unknown major versions. Pre-1.0 of egm-contracts: enum-of-one per project/schema_evolution.md.
    """

    field_1 = "1"


class Status(Enum):
    """
    Lifecycle status of the phase.
    """

    in_progress = "in_progress"
    shipped = "shipped"
    abandoned = "abandoned"


class UsageTag(Enum):
    """
    Standardized usage vocabulary for observations + figures. See cross_artifact_linkage_design.md section 8. 'in_paper_main' / 'in_paper_supplementary' are figures-only; 'informed_paper' is observations-only; the rest apply to both.
    """

    in_paper_main = "in_paper_main"
    in_paper_supplementary = "in_paper_supplementary"
    informed_paper = "informed_paper"
    exploratory = "exploratory"
    additional_example = "additional_example"
    pending = "pending"
    superseded = "superseded"
    dead_end = "dead_end"


class ArtifactId(RootModel[str]):
    root: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode, and PERMANENTLY so - the field is meaningful only for single-activation traces. It is absent whenever no single anchor exists: sliding-window extraction (no activation anchor at all), multi-beat traces (several activations, so no one position describes the trace), and any bank written before its producer's splitter shipped. Consumers MUST treat absence as 'unknown position' - never as 0.0, which is a legitimate value meaning the activation sits on the first sample, so defaulting would fabricate a spike at the low edge of the distribution.
    """


class NoiseBankEntry(BaseModel):
    """
    Manifest pointer to a noise bank (nbank_). No model / source_bank — noise banks are an additive source, never classified.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    download_url: AnyUrl | None = None
    """
    OPTIONAL. Filled at release time.
    """
    usage_notes: str | None = None


class TrainingRunEntry(BaseModel):
    """
    Manifest pointer to a training run record (run.json).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    trained_on_bank: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Relationship: run -> training bank (future edge TRAINED_ON).
    """
    produced_model: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Relationship: run -> model (future edge PRODUCED).
    """
    usage_notes: str | None = None


class ModelEntry(BaseModel):
    """
    Manifest pointer to an exported model.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    trained_from_run: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Relationship: model -> run (future edge TRAINED_FROM, inverse of PRODUCED).
    """
    download_url: AnyUrl | None = None
    """
    OPTIONAL. Filled at release time.
    """
    usage_notes: str | None = None


class ObservationEntry(BaseModel):
    """
    Manifest pointer to an observation file.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    usage_tag: UsageTag | None = None
    """
    OPTIONAL day-to-day; REQUIRED at release-gate. For observations, 'informed_paper' marks one that informed a paper claim.
    """
    usage_notes: str | None = None


class FigureEntry(BaseModel):
    """
    Manifest pointer to a figure spec file.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    consumes_banks: list[ArtifactId] | None = None
    """
    Relationship: figure -> banks it visualizes (future edge VISUALIZES). May reference egm_banks and/or noise_banks.
    """
    consumes_models: list[ArtifactId] | None = None
    """
    Relationship: figure -> models (future edge VISUALIZES_MODEL).
    """
    consumes_observations: list[ArtifactId] | None = None
    """
    Relationship: figure -> observations it illustrates (future edge BUILDS_ON).
    """
    usage_tag: UsageTag | None = None
    """
    OPTIONAL day-to-day; REQUIRED at release-gate. For figures, 'in_paper_main' / 'in_paper_supplementary' place it in the paper.
    """
    usage_notes: str | None = None


class PaperEntry(BaseModel):
    """
    Manifest pointer to a paper directory in intracardiac-papers.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    produced_by_version: str | None = None
    """
    The paper repo isn't version-tagged like the libraries; 'latest' is acceptable.
    """
    figures: list[FigureId] | None = None
    """
    Figures this paper includes.
    """
    usage_notes: str | None = None


class EgmBankEntry(BaseModel):
    """
    Manifest pointer to a bank of EGM traces (training / pretraining / prediction). The id prefix encodes the role. `model` + `source_bank` are filled only for prediction banks (lpred_ / upred_); training and pretraining banks omit them.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable cross-artifact identifier: <role_prefix>_<descriptive_name>[_<YYYY-MM-DD>][_vN]. The role prefix MUST be one of the known artifact roles (tbank_ / ptbank_ / lpred_ / upred_ / nbank_ / run_ / model_ / obs_) — the vocabulary is single-sourced in codegen/roles.json, and tests/test_roles.py asserts this pattern's alternation matches it (fig_ and paper_ are excluded here: figures and papers carry FigureId / PaperId, which are not ArtifactIds). Prefixes encode the artifact's role in the ML pipeline, not its data origin. The date suffix is OPTIONAL: auto-derived ids stamp the creation date (YYYY-MM-DD), but a hand-set id may omit it. See intracardiac-platform/project/cross_artifact_linkage_design.md section 1.
    """
    path: str
    """
    Path to the artifact file, relative to the phase folder this manifest lives in (e.g. 'banks/tbank_synthetic_v1_5.h5'). In-phase artifacts are copied under the phase folder and recorded relatively so the folder is self-contained and movable; an artifact that genuinely lives outside it may still be recorded as an absolute path, but that ties the manifest to one machine. Unconstrained string - the shape is convention, checked by the validator script, not by this schema.
    """
    produced_by_package: str | None = None
    """
    Producer package name (e.g. synthetic-egm-pipeline).
    """
    produced_by_version: str | None = None
    """
    Producer version that wrote the artifact (e.g. v0.2.0).
    """
    model: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Prediction banks only: the model that produced the predictions (future edge EVALUATED_BY).
    """
    source_bank: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Prediction banks only: the EGM bank the predictions were computed on (future edge REFERENCES_SOURCE).
    """
    download_url: AnyUrl | None = None
    """
    OPTIONAL. GitHub Release asset URL, filled at phase-release time (not write time).
    """
    usage_notes: str | None = None
    """
    OPTIONAL free-text nuance.
    """


class PhaseManifest(BaseModel):
    """
    Per-phase shallow index of every artifact that belongs to one project phase, living at intracardiac-platform/project/phases/phase_X/manifest.json. Schema version 1. Entries are POINTERS, not content: each carries only id + path + producer + relationship references (+ optional usage_tag / usage_notes / download_url). Everything else (title, description, layout, metrics, ...) lives inside the standalone file the entry points at. Banks are split by CONTENT/ROLE into two sections: `egm_banks` holds every bank of EGM traces (training tbank_, pretraining ptbank_, and prediction lpred_/upred_ banks — a prediction bank is just an EGM bank whose entry also fills `model` + `source_bank`), and `noise_banks` holds nbank_ banks of additive noise, which differ in both content and role. Relationship field names (trained_on_bank, produced_model, source_bank, consumes_banks, ...) are chosen to map 1:1 onto future provenance-graph edge types. egm-studio is the canonical curator; scripts/validate_manifest.py is the scan-and-validate safety net. Phase membership is recorded here — the artifacts it points at do not themselves declare which phase they belong to. Every entry requires only `id` + `path`: `produced_by_package` / `produced_by_version` are OPTIONAL (since egm-contracts v0.6.0), because the curator can legitimately index an artifact whose producer isn't knowable — hand-added files, externally-produced data, anything predating the convention — and writing 'unknown' / '0' sentinels to satisfy a required field made those cases indistinguishable from a real producer stamp. Producers still fill both; absence is the honest signal that nobody knows. See intracardiac-platform/project/cross_artifact_linkage_design.md sections 3 and 8.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version. Consumers MUST refuse unknown major versions. Pre-1.0 of egm-contracts: enum-of-one per project/schema_evolution.md.
    """
    phase: float
    """
    Project science-phase number this manifest indexes (e.g. 1.5, 2, 5). Numeric; the on-disk folder uses an underscore form (phase_1_5).
    """
    status: Status
    """
    Lifecycle status of the phase.
    """
    phase_summary: str | None = None
    """
    One-paragraph free-text description of what this phase is about. For human readability when opening the file cold.
    """
    egm_banks: list[EgmBankEntry] | None = None
    """
    Banks of EGM traces — training (tbank_), pretraining (ptbank_), and prediction (lpred_ labeled / upred_ unlabeled) banks. The id prefix tells the role; a prediction bank is an entry that also fills `model` + `source_bank`. All flow through the ClassifierBank structure downstream.
    """
    noise_banks: list[NoiseBankEntry] | None = None
    """
    Noise banks (nbank_) — quiet segments the synthetic mixer ADDS to EGM data. Separate from egm_banks because the content (noise, not EGM) and role (additive source, not classified data) differ.
    """
    training_runs: list[TrainingRunEntry] | None = None
    """
    Training run records (run_ prefix).
    """
    models: list[ModelEntry] | None = None
    """
    Exported models (model_ prefix).
    """
    observations: list[ObservationEntry] | None = None
    """
    Observations (obs_ prefix) — a recorded discovery, optionally pinning specific traces.
    """
    figures: list[FigureEntry] | None = None
    """
    Figure specs (fig_ prefix) — the spec file is the artifact; the rendered image is gitignored build output.
    """
    papers: list[PaperEntry] | None = None
    """
    Papers (paper_ prefix) that this phase contributes to.
    """
