# generated by codegen/gen_python.py from codegen/roles.json
#   Artifact-role vocabulary: the Role enum + the id-prefix -> Role map.
#   Single-sourced in codegen/roles.json; role_of() logic is hand-written
#   in myocard_egm_contracts/roles.py. Do NOT edit by hand — regenerate via
#   `python codegen/gen_python.py`.

from __future__ import annotations

from enum import Enum


class Role(Enum):
    training_bank = "training_bank"
    pretraining_bank = "pretraining_bank"
    labeled_prediction_bank = "labeled_prediction_bank"
    unlabeled_prediction_bank = "unlabeled_prediction_bank"
    noise_bank = "noise_bank"
    training_run = "training_run"
    model = "model"
    observation = "observation"
    figure = "figure"
    paper = "paper"


ROLE_PREFIXES: dict[str, Role] = {
    "tbank_": Role.training_bank,
    "ptbank_": Role.pretraining_bank,
    "lpred_": Role.labeled_prediction_bank,
    "upred_": Role.unlabeled_prediction_bank,
    "nbank_": Role.noise_bank,
    "run_": Role.training_run,
    "model_": Role.model,
    "obs_": Role.observation,
    "fig_": Role.figure,
    "paper_": Role.paper,
}
