# generated by datamodel-codegen:
#   filename:  run_record.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SchemaVersion(Enum):
    """
    Versioned schema identifier in <package>.<format>/<major>.<minor> form. Consumers MUST refuse unknown major versions.
    """

    field_1_0 = "1.0"


class Best(BaseModel):
    """
    Summary of the best epoch by the configured selection metric.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    epoch: int | None = Field(None, ge=1)
    """
    1-based epoch number that scored best by the selection metric.
    """
    metric: str | None = None
    """
    Metric used for selection (e.g. 'auroc', or 'neg_val_loss' as a fallback when the configured metric was non-finite on every epoch).
    """
    value: float | None = None
    """
    The metric value at the selected epoch. Null when the metric was undefined across every epoch.
    """


class ReliabilityBin(BaseModel):
    """
    One reliability-diagram bin (calibration analysis).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    lo: float = Field(..., ge=0.0, le=1.0)
    """
    Lower edge of the predicted-probability bin (in [0, 1]).
    """
    hi: float = Field(..., ge=0.0, le=1.0)
    """
    Upper edge of the predicted-probability bin (in [0, 1]).
    """
    count: int = Field(..., ge=0)
    """
    Number of samples whose predicted probability for the positive class fell in (lo, hi].
    """
    confidence: float | None
    """
    Mean predicted probability across the bin (null if count == 0).
    """
    accuracy: float | None
    """
    Empirical accuracy across the bin (null if count == 0). For a well-calibrated model, accuracy ≈ confidence in every bin.
    """


class Test(BaseModel):
    """
    Held-out test metrics, present iff a test split was evaluated.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    loss: float | None = None
    """
    Mean test-set loss across batches. Null when the test split was empty.
    """
    metrics: dict[str, float | int | None] | None = None
    """
    Scalar test metrics (auroc, accuracy, precision, recall, f1, ece, ...). Keys are metric names; values are scalars or null when the metric was undefined.
    """
    reliability: list[ReliabilityBin] | None = None
    """
    Reliability bins computed on the test split (calibration-diagram input).
    """


class EpochRecord(BaseModel):
    """
    Full per-epoch record: scalar losses, scalar metrics, calibration bins.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    epoch: int = Field(..., ge=1)
    """
    1-based epoch number, strictly increasing across the run.
    """
    lr: float = Field(..., ge=0.0)
    """
    Learning rate at the epoch's last optimizer step.
    """
    train_loss: float | None
    """
    Mean training-set loss across all batches in the epoch.
    """
    val_loss: float | None
    """
    Mean validation-set loss across all batches in the epoch.
    """
    epoch_seconds: float = Field(..., ge=0.0)
    """
    Wall-clock seconds spent on this epoch (training + validation).
    """
    val_metrics: dict[str, Any]
    """
    Scalar validation metrics for the epoch (auroc / accuracy / precision / recall / f1 / ece). Confusion-matrix counts may appear under a nested 'confusion' object with keys tp/fp/tn/fn. Additional producer-defined keys allowed.
    """
    val_reliability: list[ReliabilityBin]
    """
    Validation-split reliability bins for the calibration diagram.
    """


class RunRecord(BaseModel):
    """
    Versioned full-fidelity record of one training run, written to run.json. Schema version 1.0. All non-finite floats are emitted as null so the JSON stays strictly valid.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Versioned schema identifier in <package>.<format>/<major>.<minor> form. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    run: dict[str, Any]
    """
    Run-level metadata. Well-known keys (producer SHOULD write all of these): 'run_id' (string, unique identifier), 'git_sha' (string, repo state at training time), 'host' (string, hostname where training ran), 'model_version' (string, model architecture version tag), 'training_started_utc' / 'training_ended_utc' (ISO date-times). Additional keys allowed for forward compatibility.
    """
    config: dict[str, Any]
    """
    The fully-resolved training configuration as a flat-ish nested dict. Well-known top-level keys: 'model' (architecture + hyperparameters), 'data' (bank paths, augmentation, split ratios), 'training' (optimizer, scheduler, epochs, batch size, loss), 'eval' (selection metric, decision threshold). The contents reflect whatever the producer's config system serializes; consumers should treat unknown keys as additional context rather than fail on them.
    """
    epochs: list[EpochRecord]
    """
    Time series of per-epoch records, ordered by epoch number.
    """
    best: Best
    """
    Summary of the best epoch by the configured selection metric.
    """
    test: Test | None = None
    """
    Held-out test metrics, present iff a test split was evaluated.
    """
