# generated by datamodel-codegen:
#   filename:  synthetic_bank.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(Enum):
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """

    field_1_1 = "1.1"


class StimEdgeEnum(Enum):
    top = "top"
    bottom = "bottom"
    left = "left"
    right = "right"


class Traces(BaseModel):
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the trace count) and are aligned.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: list[list[float]]
    """
    (N, T) float32 — the bipolar EGM waveforms.
    """
    simulation_id: list[int]
    """
    (N,) int64 — patient/simulation index (the patient-aware split unit).
    """
    pair_index: list[int]
    """
    (N,) int64 — index of the bipolar electrode pair within the grid (0..n_pairs).
    """
    electrode_row: list[int]
    """
    (N,) int64 — row index within the 5x5 grid this pair belongs to.
    """
    fibrosis_density: list[float]
    """
    (N,) float64 — requested fibrosis density (continuous label, 0.0 == healthy).
    """
    fibrosis_density_realized: list[float]
    """
    (N,) float64 — actual fraction of non-conductive nodes after the substrate draw (differs from requested due to grid-size discretization).
    """
    electrode_height_mm: list[float]
    """
    (N,) float64 — height of this electrode pair above the tissue surface, in mm. Sampled uniformly per simulation from [0.2, 1.0] mm in Phase 1.
    """
    seed: list[int]
    """
    (N,) int64 — RNG seed used for this simulation (reproducibility).
    """
    snr_db: list[float]
    """
    (N,) float64 — target signal-to-noise ratio at which IAFDB noise was mixed in. NaN when mixer was off.
    """
    stim_edge: list[StimEdgeEnum]
    """
    (N,) UTF-8 — stimulation edge for the planar wave that produced this trace. Phase 1 only models planar-wave stim from a tissue edge; Phase 2 introduces point-source / S1-S2 protocols that will need a richer 'stimulation' object (type discriminator + protocol-specific params). When that schema version lands, this field is replaced (not extended); see project/known_issues.md for the migration plan.
    """
    noise_record: list[str]
    """
    (N,) UTF-8 — IAFDB record name that supplied the noise segment ('' when mixer was off).
    """
    noise_channel: list[str]
    """
    (N,) UTF-8 — IAFDB channel name that supplied the noise segment ('' when mixer was off).
    """


class FigureId(RootModel[str]):
    root: str = Field(..., pattern="^fig_[A-Za-z0-9_\\-]+$")
    """
    Figure identifier. Slug-based (hyphens allowed, no date suffix), so it does NOT match the dated ArtifactId pattern. e.g. fig_feature_distributions_synth_vs_iafdb.
    """


class PaperId(RootModel[str]):
    root: str = Field(..., pattern="^paper_[a-z0-9_]+$")
    """
    Paper identifier (e.g. paper_phase_1_5_realism). Slug-based, no date.
    """


class ActivationPosition(RootModel[float]):
    root: float = Field(..., ge=0.0, le=1.0)
    """
    Realized position of the activation within a trace, as a fraction of the trace: 0.0 = first sample, 1.0 = last sample. Rate- and length-independent by construction; convert at point of use with idx = round(frac * (T - 1)). This is the position the activation-aware splitter/crop ACTUALLY produced (the anchor it placed), not a value measured from the waveform afterwards - a consumer that wants the measured dV/dt-max position computes it with egm-features instead. Stored per trace by both corpora (iafdb_bank via IAF1, synthetic_bank via SEP2) so the synthetic-vs-IAFDB position distributions are compared stored-vs-stored rather than one stored against one recomputed. Defined once here and $ref'd by both banks so the two cannot drift. OPTIONAL-IN-SCHEMA / REQUIRED-ON-WRITE in activation mode: the Phase-1.5 Wave-1 schema migration writes banks before the splitters populate it, so absence is valid; producers enforce presence once they emit it.
    """


class SyntheticBank(BaseModel):
    """
    Synthetic intracardiac EGM bank (may include real-noise conditioning at the signal level). Schema version 1.1. Maps to an HDF5 file with bank-level root attrs plus a `traces/` group containing per-trace columns. 1.1 (from 1.0) added the optional `bank_id` stable-artifact identifier (egm-contracts v0.5.0, cross-artifact linkage).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    """
    Schema version in X.Y form. X (major) bumps at release; Y (minor) bumps on every dev-time structural change. Consumers MUST refuse unknown major versions.
    """
    created_utc: AwareDatetime
    """
    ISO-8601 UTC timestamp captured at write time.
    """
    bank_id: str | None = Field(
        None,
        pattern="^(tbank|ptbank|lpred|upred|nbank|run|model|obs)_[a-z0-9_]+(_\\d{4}-\\d{2}-\\d{2})?(_v\\d+)?$",
    )
    """
    Stable artifact ID for this bank, e.g. 'tbank_synthetic_courtemanche_v1_5_2026-06-25'. Optional for legacy banks written before egm-contracts v0.5.0; egm-data stamps it on every new bank (enforced at write time, not by this schema, per the cross-artifact-linkage 'optional-in-schema, required-on-write' decision). Added 1.1.
    """
    description: str | None = None
    """
    Free-text human-readable description of this bank's intent (e.g., 'hybrid_v1 — 100 sims, 20 traces/sim, SNR 10-25 dB').
    """
    fs_hz: float = Field(..., gt=0.0)
    """
    Sampling rate in Hz. Phase 1 is 1000.0 to match IAFDB.
    """
    trace_duration_ms: float = Field(..., gt=0.0)
    """
    Per-trace duration in milliseconds.
    """
    simulator: str
    """
    Simulator backend identifier. Phase 1 = 'finitewave'.
    """
    cell_model: str
    """
    Cellular electrophysiology model. Phase 1 = 'aliev_panfilov'.
    """
    patch_size_mm: float | None = Field(None, ge=0.0)
    """
    Tissue patch side length in mm (square patch). Phase 1 = 40 mm.
    """
    patch_dr_mm: float | None = Field(None, gt=0.0)
    """
    Spatial discretization step in mm. Phase 1 = 0.25 mm.
    """
    ap_time_unit_ms: float | None = Field(None, ge=0.0)
    """
    Mapping from simulator's non-dimensional time to ms (Aliev-Panfilov-specific; 0 for fully dimensional simulators).
    """
    fibrosis_strategy_name: str
    """
    Identifier for the fibrosis substrate generation strategy. Phase 1 = 'uniform_random'.
    """
    fibrosis_params: dict[str, Any] | None = None
    """
    Parameters of the fibrosis strategy. Stored on HDF5 as a JSON-encoded string attr (`fibrosis_params_json`) since HDF5 attrs are flat. Schema models the decoded structure.
    """
    electrode_config: dict[str, Any] | None = None
    """
    Electrode grid configuration (grid shape, spacing, height range). Stored on HDF5 as JSON in `electrode_config_json`.
    """
    mixer_config: dict[str, Any] | None = None
    """
    Noise mixer configuration (target SNR range, band, on/off knob). Stored on HDF5 as JSON in `mixer_config_json`.
    """
    experiment_config: dict[str, Any] | None = None
    """
    Top-level experiment knobs that drove this bank's generation. Stored on HDF5 as JSON in `experiment_config_json`.
    """
    noise_bank_source: str | None = None
    """
    Identifier of the IAFDB noise bank consumed by the mixer (e.g., 'iafdb_noise_v1.h5').
    """
    traces: Traces
    """
    Per-trace columns. Maps to the HDF5 `traces/` group. All columns have first dimension N (the trace count) and are aligned.
    """
